permissions:
  contents: read

name: main-workflow

on:
  workflow_dispatch: 

jobs:
  trigger-L1:
    uses: ./.github/workflows/L1-tests.yml
    with:
      caller_source: local

  trigger-L2:
    uses: ./.github/workflows/L2-tests.yml
    with:
      caller_source: local
